# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sawyer Bernath's website
tagline:          
description:      
url:              https://sawyerbernath.github.io/
baseurl:          /

author:
  name:           'Sawyer Bernath'
  url:            https://sawyerbernath.com

paginate:         5
